`define MICROSTEPPING_INTERVAL_1 3'd0
`define MICROSTEPPING_INTERVAL_1_4 3'd1
`define MICROSTEPPING_INTERVAL_1_8 3'd2
`define MICROSTEPPING_INTERVAL_1_16 3'd3
`define MICROSTEPPING_INTERVAL_1_32 3'd4
`define MICROSTEPPING_INTERVAL_1_64 3'd5
`define MICROSTEPPING_INTERVAL_1_128 3'd6
`define MICROSTEPPING_INTERVAL_1_256 3'd7

`define MICROSTEPPING_INCREMENT_1 9'd256
`define MICROSTEPPING_INCREMENT_1_4 9'd64
`define MICROSTEPPING_INCREMENT_1_8 9'd32
`define MICROSTEPPING_INCREMENT_1_16 9'd16
`define MICROSTEPPING_INCREMENT_1_32 9'd8
`define MICROSTEPPING_INCREMENT_1_64 9'd4
`define MICROSTEPPING_INCREMENT_1_128 9'd2
`define MICROSTEPPING_INCREMENT_1_256 9'd1


`define H_BRIDGE_OFF 2'd0
// Defined as going from the left high-side driver to the right low-side driver (left to right)
`define H_BRIDGE_DRIVE_POS 2'd1
// Defined as going from the right high-side driver to the left low-side driver (right to left)
`define H_BRIDGE_DRIVE_NEG 2'd2
`define H_BRIDGE_SLOW_DECAY 0
`define H_BRIDGE_FAST_DECAY 1
